/**
 * Demo portal staff definitions for tenant seeding.
 * Each entry maps to an HMS portal (mobile or sidebar).
 */
const PORTAL_STAFF_SEED = [
  {
    type: "Doctor",
    userId: "doctor",
    password: "Doctor@123",
    name: "Dr. Demo Doctor",
    email: "doctor@demo.hospital",
    phone: "9000000001",
    gender: "Male",
    department: "General Medicine",
    position: "Consultant Physician",
    qualification: "MBBS, MD",
    specialization: "General Medicine",
    opCharges: "500",
    ipCharges: "1000",
    portal: "mobile-doctor",
  },
  {
    type: "Nurse",
    userId: "nurse",
    password: "Nurse@123",
    name: "Demo Nurse",
    email: "nurse@demo.hospital",
    phone: "9000000002",
    gender: "Female",
    department: "Nursing",
    position: "Staff Nurse",
    qualification: "BSc Nursing",
    portal: "mobile-nurse",
  },
  {
    type: "Pharmacist",
    userId: "pharmacist",
    password: "Pharmacist@123",
    name: "Demo Pharmacist",
    email: "pharmacist@demo.hospital",
    phone: "9000000003",
    gender: "Male",
    department: "Pharmacy",
    position: "Chief Pharmacist",
    qualification: "BPharm",
    licenseNumber: "PH-2024-001",
    portal: "sidebar-pharmacy",
  },
  {
    type: "LabTechnician",
    userId: "labtech",
    password: "LabTech@123",
    name: "Demo Lab Technician",
    email: "labtech@demo.hospital",
    phone: "9000000004",
    gender: "Male",
    department: "Laboratory",
    position: "Lab Technician",
    qualification: "DMLT",
    labCertification: "LAB-CERT-001",
    portal: "sidebar-lab",
  },
  {
    type: "Phlebotomist",
    userId: "phlebotomist",
    password: "Phlebotomist@123",
    name: "Demo Phlebotomist",
    email: "phlebotomist@demo.hospital",
    phone: "9000000005",
    gender: "Female",
    department: "Laboratory",
    position: "Phlebotomist",
    qualification: "Certified Phlebotomist",
    portal: "sidebar-lab",
  },
  {
    type: "Receptionist",
    userId: "receptionist",
    password: "Receptionist@123",
    name: "Demo Receptionist",
    email: "receptionist@demo.hospital",
    phone: "9000000006",
    gender: "Female",
    department: "Front Desk",
    position: "Receptionist",
    qualification: "Graduate",
    portal: "sidebar-reception",
  },
  {
    type: "Accountant",
    userId: "accountant",
    password: "Accountant@123",
    name: "Demo Accountant",
    email: "accountant@demo.hospital",
    phone: "9000000007",
    gender: "Male",
    department: "Finance",
    position: "Accountant",
    qualification: "BCom, CA Inter",
    portal: "sidebar-finance",
  },
  {
    type: "Admin",
    userId: "admin",
    password: "Admin@123",
    name: "Demo Admin",
    email: "admin@demo.hospital",
    phone: "9000000008",
    gender: "Male",
    department: "Administration",
    position: "Hospital Admin",
    qualification: "MBA",
    adminLevel: "Hospital",
    portal: "sidebar-admin",
  },
  {
    type: "HR Manager",
    userId: "hrmanager",
    password: "HRManager@123",
    name: "Demo HR Manager",
    email: "hr@demo.hospital",
    phone: "9000000009",
    gender: "Female",
    department: "Human Resources",
    position: "HR Manager",
    qualification: "MBA HR",
    portal: "sidebar-hr",
  },
  {
    type: "IT Support",
    userId: "itsupport",
    password: "ITSupport@123",
    name: "Demo IT Support",
    email: "it@demo.hospital",
    phone: "9000000010",
    gender: "Male",
    department: "Information Technology",
    position: "IT Support",
    qualification: "BTech",
    portal: "sidebar-it",
  },
  {
    type: "PRO",
    userId: "pro",
    password: "PRO@123",
    name: "Demo PRO",
    email: "pro@demo.hospital",
    phone: "9000000011",
    gender: "Male",
    department: "Marketing",
    position: "Patient Relations Officer",
    qualification: "Graduate",
    portal: "sidebar-pro",
  },
];

/** Optional demo SuperAdmin — only created when none exists in tenant */
const SUPERADMIN_SEED = {
  type: "SuperAdmin",
  userId: "superadmin",
  password: "SuperAdmin@123",
  name: "Demo Super Admin",
  email: "superadmin@demo.hospital",
  phone: "9000000000",
  gender: "Male",
  department: "Administration",
  position: "Super Administrator",
  portal: "sidebar-full",
};

module.exports = { PORTAL_STAFF_SEED, SUPERADMIN_SEED };
